<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOdTTfSM\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOdTTfSM/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerOdTTfSM.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerOdTTfSM\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerOdTTfSM\appAppKernelProdContainer([
    'container.build_hash' => 'OdTTfSM',
    'container.build_id' => 'ed5a784a',
    'container.build_time' => 1710519084,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOdTTfSM');
