<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6cLzvp7mrBBGmx+m2DtD'."\n".'0jN8AX/jaB5NNQn93YDJxb0buXW6N9c3RJYOw8km5sLgPE4fiDzgSM0tdNMXA1mc'."\n".'g6DqmM/f0Kw5YE+sWO0YbDAWXd+LY88F6c0JwgzyufN4+THh7vyLmFn8e0h9jGMO'."\n".'VgqP+FZmtbooYCHjxfAsibDUCZYiDk3PAL4/XZLiYxfJMtEVqVU6soqQPv6Sgfoj'."\n".'Ppd9O+S7qOrXBuyXNvDT73LB9SJWN+uDR6R3X+MYel+I53hCw+dtyPQHsNInQXz0'."\n".'s6zmyZIfBrubhHFPHreFoHPRaM21pA6ihcUPELR5HgZiSTtwdqgQet+EYqSSVl74'."\n".'yQIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
