<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3HQIZai\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3HQIZai/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3HQIZai.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\Container3HQIZai\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \Container3HQIZai\appAppKernelDevDebugContainer([
    'container.build_hash' => '3HQIZai',
    'container.build_id' => 'e8422f0d',
    'container.build_time' => 1710549159,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3HQIZai');
